Altairis.AskMe.Web.RazorPages/Components/MenuViewComponent.cs
namespace Altairis.AskMe.Web.RazorPages.Components;

public class MenuViewComponent : ViewComponent {
    public IViewComponentResult Invoke() {
        if (this.User.Identity?.IsAuthenticated ?? false) {
            return this.View("Authenticated");
        } else {
            return this.View("Anonymous");
        }
    }

}

Altairis.AskMe.Web.RazorPages/Components/PagerViewComponent.cs
using Altairis.AskMe.Web.RazorPages.Models;

namespace Altairis.AskMe.Web.RazorPages.Components;

public class PagerViewComponent : ViewComponent {

    public IViewComponentResult Invoke(PagingInfo model) => this.View(model);

}

Altairis.AskMe.Web.RazorPages/Pages/Index.cshtml.cs
using Altairis.AskMe.Web.RazorPages.Models;
using Microsoft.Extensions.Options;

namespace Altairis.AskMe.Web.RazorPages.Pages;

public class IndexModel : PagedPageModel<Question> {
    private readonly AskDbContext dc;
    private readonly AppSettings cfg;
    private readonly IQueryable<Question> dataSource;

    // Constructor

    public IndexModel(AskDbContext dc, IOptionsSnapshot<AppSettings> optionsSnapshot) {
        this.dc = dc;
        this.cfg = optionsSnapshot.Value;
        this.dataSource = this.dc.Questions
            .Include(x => x.Category)
            .Where(x => x.DateAnswered.HasValue)
            .OrderByDescending(x => x.DateAnswered);
    }

    // Handlers

    public async Task<ActionResult> OnGetAsync(int pageNumber) {
        // If no users are defined, redirect to first run page
        if (!await this.dc.Users.AnyAsync()) return this.RedirectToPage("FirstRun");

        await base.GetData(this.dataSource, pageNumber, this.cfg.PageSize);
        return this.Page();
    }
}

Altairis.AskMe.Web.RazorPages/Pages/Question.cshtml.cs
namespace Altairis.AskMe.Web.RazorPages.Pages;

public class QuestionModel(AskDbContext dc) : PageModel {

    // Model properties

    public Question Data { get; set; } = null!;

    // Handlers

    public async Task<IActionResult> OnGetAsync(int questionId) {
        var data = await dc.Questions.Include(x => x.Category).SingleOrDefaultAsync(x => x.Id == questionId);
        if (data == null) return this.NotFound();
        this.Data = data;
        return this.Page();
    }
}

Altairis.AskMe.Web.RazorPages/Pages/Contact.cshtml
@page
@{ this.ViewBag.Title = "Kontakt"; }

<h2><i class="fas fa-envelope"></i> Kontakt</h2>
<p>Toto je ukázová aplikace pro technologii ASP.NET Core Razor Pages. Využívá zejména:</p>
<ul>
    <li>ASP.NET Core</li>
    <li>ASP.NET Razor Pages</li>
    <li>Entity Framework Core</li>
    <li>SQLite</li>
    <li>ASP.NET Identity</li>
</ul>

<h3><i class="fas fa-user"></i> Autor</h3>
<p>Autorem je Michal A. Valášek - Altairis, s. r. o.</p>
<ul>
    <li><a href="https://www.rider.cz/">www.rider.cz</a></li>
    <li><a href="https://www.aspnet.cz/">www.aspnet.cz</a></li>
    <li><a href="https://www.altairis.cz/">www.altairis.cz</a></li>
</ul>

<h3><i class="fas fa-cog"></i> Projekt</h3>
<p>Tento projekt je open source. Další informace najdete na <a href="https://github.com/ridercz/AskMe">GitHubu</a>.</p>

Altairis.AskMe.Web.RazorPages/Pages/FirstRun.cshtml
@page
@model Altairis.AskMe.Web.RazorPages.Pages.FirstRunModel
@{
    this.ViewBag.Title = "První spuštění";
}
<section class="form">
    <header>
        <h2>První spuštění - vytvoření uživatele</h2>
    </header>
    <form method="post">
        <div>
            <input asp-for="Input.UserName" placeholder="Uživatelské jméno" />
            <input asp-for="Input.Password" placeholder="Heslo" class="half-width" />
            <input asp-for="Input.PasswordConfirmation" placeholder="Kontrola hesla" class="half-width" />
        </div>
        <div class="field">
            <input asp-for="Input.SeedDemoData" />
            <label asp-for="Input.SeedDemoData">vygenerovat ukázková data</label>
        </div>
        <div asp-validation-summary="All"></div>
        <footer>
            <input type="submit" value="Vytvořit uživatele" />
        </footer>
    </form>
</section>

Altairis.AskMe.Web.RazorPages/Pages/Index.cshtml
@page "{pageNumber:int:min(1)=1}"
@model IndexModel

@foreach (var item in Model.Data) {
    var id = $"q_{item.Id}";
    <article class="answer" id="@id">
        <section class="question">
            <header>
                <span class="fa-stack fa-lg">
                    <i class="fas fa-square fa-stack-2x"></i>
                    <i class="fas fa-question fa-stack-1x fa-inverse"></i>
                </span>
                <span class="info">
                    <i class="fas fa-tag"></i> @item.Category.Name
                    <i class="fas fa-calendar"></i> <a asp-page="Question" asp-route-questionId="@item.Id"><time value="@item.DateCreated"></time></a>
                    @if (!string.IsNullOrWhiteSpace(item.DisplayName)) {
                        <span><i class="fas fa-user"></i> @item.DisplayName</span>
                    }
                </span>
            </header>
            <plainText text="@item.QuestionText" html-encode="true"></plainText>
        </section>
        <section class="answer">
            <header>
                <span class="fa-stack fa-lg">
                    <i class="fas fa-square fa-stack-2x"></i>
                    <i class="fas fa-comment fa-stack-1x fa-inverse"></i>
                </span>
                <span class="info">
                    <i class="fas fa-calendar"></i> <time value="@item.DateAnswered"></time>
                </span>
            </header>
            <plainText text="@item.AnswerText" html-encode="true"></plainText>
            <footer for-login-status="true">
                <a asp-page="Admin/EditQuestion" asp-route-questionId="@item.Id" class="button"><i class="fas fa-commenting"></i> Upravit</a>
            </footer>
        </section>
    </article>
}
<vc:pager model="Model.Paging"></vc:pager>

Altairis.AskMe.Web.RazorPages/Pages/Question.cshtml
@page "/question/{questionId:int:min(1)}"
@model QuestionModel
@{ this.ViewBag.Title = $"Otázka číslo {Model.Data.Id}"; }

<article class="answer">
    <section class="question">
        <header>
            <span class="fa-stack fa-lg">
                <i class="fas fa-square fa-stack-2x"></i>
                <i class="fas fa-question fa-stack-1x fa-inverse"></i>
            </span>
            <span class="info">
                <i class="fas fa-tag"></i> @Model.Data.Category.Name
                <i class="fas fa-calendar"></i> <time value="@Model.Data.DateCreated"></time>
                @if (!string.IsNullOrWhiteSpace(Model.Data.DisplayName)) {
                    <span><i class="fas fa-user"></i> @Model.Data.DisplayName</span>
                }
            </span>
        </header>
        <plainText text="@Model.Data.QuestionText" html-encode="true"></plainText>
    </section>
    <section class="answer">
        <header>
            <span class="fa-stack fa-lg">
                <i class="fas fa-square fa-stack-2x"></i>
                <i class="fas fa-comment fa-stack-1x fa-inverse"></i>
            </span>
            <span class="info">
                <i class="fas fa-calendar"></i> <time value="@Model.Data.DateAnswered"></time>
            </span>
        </header>
        @if (string.IsNullOrWhiteSpace(Model.Data.AnswerText)) {
            <p>Otázka dosud nebyla zodpovězena.</p>
        }
        else {
            <plainText text="@Model.Data.AnswerText" html-encode="true"></plainText>
        }
        <footer for-login-status="true">
            <a asp-page="Admin/EditQuestion" asp-route-questionId="@Model.Data.Id" class="button"><i class="fas fa-commenting"></i> Upravit</a>
            <a asp-page="Admin/DeleteQuestion" asp-route-questionId="@Model.Data.Id" class="button"><i class="fas fa-trash"></i> Smazat</a>
        </footer>
    </section>
</article>

Altairis.AskMe.Web.RazorPages/Pages/Questions.cshtml
@page "{pageNumber:int:min(1)=1}"
@model QuestionsModel
@{ this.ViewBag.Title = "Nezodpovězené otázky"; }

<section class="form" id="ask" for-login-status="false">
    <form method="post">
        <header>
            <h2>Nová otázka</h2>
        </header>
        <div><textarea asp-for="Input.QuestionText" placeholder="Zadejte text své otázky..."></textarea></div>
        <div>
            <select asp-for="Input.CategoryId" asp-items="Model.Categories"></select>
        </div>
        <div>
            <input asp-for="Input.DisplayName" placeholder="Jméno (nepovinné)" class="half-width" />
            <input asp-for="Input.EmailAddress" placeholder="E-mail (nepovinné)" class="half-width" />
        </div>
        <div asp-validation-summary="All"></div>
        <footer>
            <input type="submit" value="Odeslat" />
        </footer>
    </form>
</section>
@if (Model.Paging.TotalRecords > 0) {
    <h2>Nezodpovězené otázky</h2>
    @foreach (var item in Model.Data) {
        var id = $"q_{item.Id}";
        <article class="question" id="@id">
            <header>
                <span class="fa-stack fa-lg">
                    <i class="fas fa-square fa-stack-2x"></i>
                    <i class="fas fa-question fa-stack-1x fa-inverse"></i>
                </span>
                <span class="info">
                    <i class="fas fa-tag"></i> @item.Category.Name
                    <i class="fas fa-calendar"></i> <time value="@item.DateCreated"></time>
                    @if (!string.IsNullOrWhiteSpace(item.DisplayName)) {
                        <span><i class="fas fa-user"></i> @item.DisplayName</span>
                    }
                </span>
            </header>
            <plainText text="@item.QuestionText" html-encode="true"></plainText>
            <footer for-login-status="true">
                <a asp-page="Admin/EditQuestion" asp-route-questionId="@item.Id" class="button"><i class="fas fa-commenting"></i> Odpovědět</a>
                <a asp-page="Admin/DeleteQuestion" asp-route-questionId="@item.Id" class="button"><i class="fas fa-trash"></i> Smazat</a>
            </footer>
        </article>
    }
    <vc:pager model="Model.Paging"></vc:pager>
}

Altairis.AskMe.Web.RazorPages/Pages/_Layout.cshtml
@inject Microsoft.AspNetCore.Hosting.IWebHostEnvironment Environment
@inject Microsoft.Extensions.Options.IOptions<AppSettings> Options
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@(string.IsNullOrWhiteSpace(ViewBag.Title) ? this.Options.Value.Title : ViewBag.Title + " | " + this.Options.Value.Title)</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.min.css" integrity="sha256-l85OmPOjvil/SOvVt3HnSSjzF1TUMyT9eV0c2BzEGzU=" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="alternate" type="application/rss+xml" title="RSS" href="@Url.RouteUrl("RssFeed")" />
    <environment include="Development">
        <link rel="stylesheet" type="text/css" href="~/Styles/askme.css" asp-append-version="true" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" type="text/css" href="~/Styles/askme.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <header>
        <h1>@this.Options.Value.Title</h1>
        <div>@this.Options.Value.Subtitle</div>
    </header>
    <vc:menu></vc:menu>
    <main>
        @RenderBody()
    </main>
    <footer>
        <ul>
            <li>Copyright &copy; <a href="https://www.altairis.cz/">Altairis</a>, 2017-@DateTime.Today.Year</li>
            <li title="@Environment.EnvironmentName environment">Using ASP.NET Razor Pages</li>
            <li><a asp-route="RssFeed"><i class="fas fa-rss"></i> RSS</a></li>
            <li for-login-status="false"><a asp-page="Account/Login">&pi;</a></li>
        </ul>
    </footer>
</body>
</html>